// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfTvzoAh6-nH13NNOs4c6VGZbxxNWxsXs',
    appId: '1:198832466265:web:e2d2fe3ffa4c83683c4448',
    messagingSenderId: '198832466265',
    projectId: 'coffeeapp-63caf',
    authDomain: 'coffeeapp-63caf.firebaseapp.com',
    storageBucket: 'coffeeapp-63caf.appspot.com',
    measurementId: 'G-HJ34NW07VS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_D8blzd89UBC5l9S_7BU_W6VntJ_d_No',
    appId: '1:198832466265:android:6b02e1aeaa4e5e803c4448',
    messagingSenderId: '198832466265',
    projectId: 'coffeeapp-63caf',
    storageBucket: 'coffeeapp-63caf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQpfdz395pjyYCKtWMpv2C6iXJRX1ZcaM',
    appId: '1:198832466265:ios:139230858c4e8ffd3c4448',
    messagingSenderId: '198832466265',
    projectId: 'coffeeapp-63caf',
    storageBucket: 'coffeeapp-63caf.appspot.com',
    iosBundleId: 'com.example.coffeeappui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQpfdz395pjyYCKtWMpv2C6iXJRX1ZcaM',
    appId: '1:198832466265:ios:c81f1f280a3335dc3c4448',
    messagingSenderId: '198832466265',
    projectId: 'coffeeapp-63caf',
    storageBucket: 'coffeeapp-63caf.appspot.com',
    iosBundleId: 'com.example.coffeeappui.RunnerTests',
  );
}
